name: "Modernum QA Demo Project: Start Tests"
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Choose environment to test'
        required: true
        type: choice
        default: 'PRODUCTION'
        options:
          - PRODUCTION
          - STAGE
concurrency:
  group: ModernumQADemoProjectGroup
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Run command on remote server
        uses: D3rHase/ssh-command-action@v0.2.2
        with:
          host: ${{secrets.SSH_HOST}}
          user: ${{secrets.SSH_USER}}
          private_key: ${{secrets.SSH_PRIVATE_KEY}}
          command: |
              /home/kate/git/QA-Demo-Project/server_scripts/run_tests.sh -e "${{ github.event.inputs.environment }}" > /var/log/QA-Demo-Project.log 2>&1

permissions:
  contents: read
  actions: read
  issues: write